name: Docker Image CI Yocto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yocto-image:$(date +%s)
    
    - name: Run script inside container
      run: docker run --rm yocto-image:$(date +%s) ./run_build.sh
        # Replace ./my-script.sh with your script path inside the container
