name: Docker based yocto build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set timestamp
      run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yocto-image:$TIMESTAMP

    - name: Run script inside container
      run: docker run --rm yocto-image:$TIMESTAMP /home/yoctouser/run_build.sh
        # Replace ./my-script.sh with your script path inside the container
